### ISSUE TITLE
windows compatibilities

### ISSUE THREAD

**Issue by tapj** [omixer/omixer-rpmR#2]
I tried to run your example on windows 

(I installed myself the jar code on java folder see [1](https://github.com/omixer/omixer-rpmR/issues/1))

however I had this error now:

```
> library(omixerRpm)
> # read a functional profile matrix into R or create it inside R
> dat <- read.table("test/matrix.tsv", header=T, sep="\t")
> # Run the module mapping on the loaded table.
> mods <- rpm(dat, minimum.coverage=0.3, annotation = 1)
Error in file(file, "rt") : cannot open the connection
In addition: Warning messages:
1: running command 'java -jar C:/Users/jtap/Documents/R/R-3.4.1/library/omixerRpm/java/omixer-rpm.jar -c 0.3 -s median -d C:/Users/jtap/Documents/R/R-3.4.1/library/omixerRpm/extdata/GMMs.v1.07.txt -i C:\Users\jtap\AppData\Local\Temp\RtmpG83sYA\file28d41b752272/input.tsv -o C:\Users\jtap\AppData\Local\Temp\RtmpG83sYA\file28d44d086a43 -a 1 -t 1 -e 2' had status 127 
2: In file(file, "rt") :
  cannot open file 'C:\Users\jtap\AppData\Local\Temp\RtmpG83sYA\file28d44d086a43/modules.tsv': No such file or directory
```
I suspect something about the path, not correctly called for windows system. "/" vs "\" with **the status 127**.

**Comment by omixer** [comment]
I am using file.path() and other built-in commands for accessing files so it should work on windows as well!    

Could you please send me the output of this command? it should have more info than status 127!
 
java -jar C:/Users/jtap/Documents/R/R-3.4.1/library/omixerRpm/java/omixer-rpm.jar -c 0.3 -s median -d C:/Users/jtap/Documents/R/R-3.4.1/library/omixerRpm/extdata/GMMs.v1.07.txt -i C:\Users\jtap\AppData\Local\Temp\RtmpG83sYA\file28d41b752272/input.tsv -o C:\Users\jtap\AppData\Local\Temp\RtmpG83sYA\file28d44d086a43 -a 1 -t 1 -e 2

and also the first 3 lines of C:\Users\jtap\AppData\Local\Temp\RtmpG83sYA\file28d41b752272/input.tsv

**Comment by tapj** [comment]
ok I reinstalled it from the master.zip and the probleme was solved.
