### ISSUE TITLE
Error when working with large datasets

### ISSUE THREAD

**Issue by Benjamin-Valderrama** [omixer/omixer-rpmR#5]
Hi,

I'm using your R package with a (seemingly) too large dataset. It has > 6,900 columns (different bacterial genomes) and > 10,000 rows (different KOs present in the bacterial genomes). When I run the rpm function with that dataset, after spending some time computing, it crashes and shows the following error:

```
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at sun.misc.FloatingDecimal.readJavaFormatString(Unknown Source)
	at sun.misc.FloatingDecimal.parseDouble(Unknown Source)
	at java.lang.Double.parseDouble(Unknown Source)
	at java.lang.Double.valueOf(Unknown Source)
	at org.omixer.rpm.parsers.FunctionLineProcessor.process(FunctionLineProcessor.java:49)
	at org.omixer.utils.utils.FileUtils.readMatrix(FileUtils.java:235)
	at org.omixer.rpm.service.impl.ModuleManagerImpl.inferModules(ModuleManagerImpl.java:173)
	at org.omixer.rpm.core.InferenceApp.main(InferenceApp.java:252)

Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") :
  cannot open file 'C:\Users\BVALDE~1\AppData\Local\Temp\RtmpqcBd0h\file1e406c471c1f/modules.tsv': No such file or directory

```
I have been using your package for around 2 months with smaller datasets and It never happened before, so after a quick search in the internet I found that what can be happening is that the computation times to analyze the entire dataset would be too long. 

Is it possible  to overcome this difficulty within R? I ran the same script in my personal computer and in a server and in both cases the script crashes after working for a while.

--- 

R and OS info:

platform       x86_64-w64-mingw32                              
arch           x86_64                                          
os             mingw32                                         
crt            ucrt                                            
system         x86_64, mingw32                                 
status         Patched                                         
major          4                                               
minor          2.0                                             
year           2022                                            
month          05                                              
day            19                                              
svn rev        82383                                           
language       R                                               
version.string R version 4.2.0 Patched (2022-05-19 r82383 ucrt)
nickname       Vigorous Calisthenics     

Also, I'm using the 0.3.2 version of the `omixerRpm` package

**Comment by omixer** [comment]
Hi Benjamin,

Thank you for reporting this issue!

Did you try to increase the memory available to `rpm`? You can increase it by changing the `java.mem` parameter. You can also increase the number of threads to speedup the computation (if you type `?rpm` in R you will have all the documentation)!
Try using 16G for mem and 16 threads.

I hope this will solve your problem, and please let me know how it goes!

Best regards,
Youssef

**Comment by Benjamin-Valderrama** [comment]
It worked perfectly, thank you so much for the answer.
