### ISSUE TITLE
"The execution of Omixer-RPM returned a non-zero exit status. Refer to the exception output for details." Errore in doTryCatch(return(expr), name, parentenv, handler) :  The execution of Omixer-RPM returned a non-zero exit status. Refer to the exception output for details.

### ISSUE THREAD

**Issue by LuisaTurco** [omixer/omixer-rpmR#9]
Hi everyone!!

I am having a bit of a problem when running omixer-rpm. After sending the following command "mods <- rpm(dat, minimum.coverage= 0.6, annotation = 2)", I received this error: 
"The execution of Omixer-RPM returned a non-zero exit status. Refer to the exception output for details.
Error in doTryCatch(return(expr), name, parentenv, handler) :  The execution of Omixer-RPM returned a non-zero exit status. Refer to the exception output for details."

Can anyone help me with this issue? Thank you!!!!!

**Comment by omixer** [comment]
Hi @LuisaTurco,

Was there any additional error info after this message ? 
Could you please share a subset of your data for testing?

Thanks,
Youssef
